### ISSUE TITLE
Environment provisioning

### ISSUE THREAD

**Issue by m8pple** [POETSII/pml#1]
Your readme includes info on using a virtualenv to setup the jinja2
and docopt packages (which works perfectly), but it might also be useful
to provide a provisioning script to get system packages (e.g. for use within
vagrant). Looking at it that could be something like:
```
while read x ; do
    sudo apt install python-${x};
done < requirements.txt
```
(completely untested)

(Not that I have a problem with virtualenv or the problem it is solving, it's
just that for efficiency reasons the system packages can be useful)

**Comment by gtarawneh** [comment]
Thanks for the suggestion. `pip` can be used without `virtualenv` and is the [recommended tool](https://packaging.python.org/guides/tool-recommendations/) to install Python packages. `pip install -r requirements.txt` does what the loop above is meant to do.

I have updated README to clarify that `pml` can be installed without `virtualenv`.
