### ISSUE TITLE
Readme instructions out of date?

### ISSUE THREAD

**Issue by m8pple** [POETSII/pml#2]
The example in the readme says to do:
```
wget -q https://poets-project.org/download/n3.graphml
./pml.py gen templates/fantasi.xml n3.graphml > poets.xml
```
but then I get:
```
ubuntu@ubuntu-xenial:/POETS/pml$ ./pml.py gen templates/fantasi.xml n3.graphml > poets.xml
Usage:
  pml.py <app.json> <file.graphml>
```

I poked around, and found that this worked:
```
./pml.py traverse1/app.json n3.graphml > poets.xml
```
though haven't tried running the output yet (I just wanted to see what it looked like).

Possibly it's just off a different branch or something.

**Comment by gtarawneh** [comment]
Thanks, yes it's temporarily out of date. I've moved sections that require updating to a separate file for now and will be working on updating and moving them back to README soon.
